apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-python-web-app-pull-request
  namespace: default
annotations:
  pipelinesascode.tekton.dev/on-target-branch: "[main]"
  pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  pipelineSpec:
    tasks:
    - name: clone
      taskSpec:
        steps:
        - name: clone
          image: alpine
          script: |
            echo "Get the code"
