apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-python-web-app-push
  namespace: default
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main"
spec:
  params:
  - name: git_url
    value: "{{ repo_url }}"
  - name: revision
    value: "{{ revision }}"
  pipelineRef:
    name: build-pipeline
